### ISSUE TITLE
Add ability to specify new arguments for both the player and Streamlink

### ISSUE THREAD

**Issue by gyvess** [Foldex/reflex-curses#1]
I have multiple settings that make streams run more smoothly and with lower latency than the default settings. This includes an `mpv` profile specifically for twitch as well as a handful of `streamlink` arguments, however these are inaccessible when using `reflex-curses`.

It'd also be nice if this can be set, not only globally, but also on a per channel basis.

**Comment by Foldex** [comment]
As for setting this globally, seems reasonable. 

I've pushed a commit that changes how arguments are handled, as well as adding a `streamlink` option. Instead of having two options, -- one for the executable and the other for an argument -- I've merged them into a single option, this also comes with the added benefit of supporting multiple arguments instead of just a single one. Let me know if you run into any issues with this, if not I can bump the release up.

This is however, a breaking change that will require updating your config file to match (or you can just nix the `[exec]` section and let reflex rebuild it). It should look like:
```
[exec]
browser = firefox --new-window
chat_method = browser
player = mpv --force-window=yes
streamlink = streamlink -t '{author} - {title}' --twitch-disable-hosting 
term = urxvt -e
```

Per channel I'm less than sold on, as I'd rather not overcomplicate things. What would be an example use case for it?

As a curious aside, what would your options for mpv/streamlink be? If they're reasonable defaults I could always merge them in.

**Comment by gyvess** [comment]
I've just tested it out, arguments for `mpv` work but arguments for `streamlink` don't. Using `htop` I can see that the arguments for `streamlink` remain the same regardless of what I've changed in the config.

As for per channel uses, some channels I follow I might want to always have a lower quality set for a specific channel. For example, having audio only for music streams I'd only listen to. As for per channel 'mpv' options, for channels I know to have volume issues I may want to launch the channel with `af="lavfi=[dynaudnorm=f=200:g=5:r=0.2]"` to normalize the volume. I wouldn't usually want this option enabled globally though, because it causes a stream delay.

My options for mpv/streamlink are tailored specifically for low latency and probably over kill. I use the low latency `streamlink` patch from bastimeyer which seems to be in a freeze, but I've still been able to patch the latest version of `streamlink` with it. The patch brings along one or two extra arguments not applicable for most people.

**Comment by Foldex** [comment]
> Using `htop` I can see that the arguments for `streamlink` remain the same regardless of what I've changed in the config.

I can't reproduce this, did you perhaps edit the config file while reflex was open? Reflex saves the configuration on exit, so if you edit it while relflex is open, it will wipe your changes.

> As for per channel uses, some channels I follow I might want to always have a lower quality set for a specific channel. For example, having audio only for music streams I'd only listen to. As for per channel 'mpv' options, for channels I know to have volume issues I may want to launch the channel with `af="lavfi=[dynaudnorm=f=200:g=5:r=0.2]"` to normalize the volume. I wouldn't usually want this option enabled globally though, because it causes a stream delay.

Per channel quality I can see being the most commonly useful, and would be the most straightforward to implement. Per channel arguments would likely require a config file format change though, both to easily handle multiple arguments and to simply remain easily readable. I had already considered making the followed list conform to the same format as the config file, or using a local database though. So maybe it would be best to make the change while it's still early on.

Can't promise when I'll get around to that however. For a short term hacky fix, you could simply point `[exec]` to a wrapper script  instead of the actual executable to handle the arguments. Less than ideal though.

> My options for mpv/streamlink are tailored specifically for low latency and probably over kill. I use the low latency `streamlink` patch from bastimeyer which seems to be in a freeze, but I've still been able to patch the latest version of `streamlink` with it. The patch brings along one or two extra arguments not applicable for most people.

Ah, guess not much is applicable for widespread use. The patch does sound interesting though.

**Comment by gyvess** [comment]
Building from the AUR I can see that the python file didn't properly change. Reinstalled several times while clearing cache, still no dice so maybe there is something wrong with my setup. I've directly copied the changes from git now and the `streamlink` arguments work perfectly now. Sorry wasting your time checking out a problem that didn't exist.

A wrapper could probably work, but I'd have to think about it heh. Probably if statements and simple grepping, but my worry is whether `reflex-curses` reports what channel it is launching so I can use a positional argument. I'll try and figure it out later.

In any case, this is a really solid project. I'm switching from `streamlink-twitch-gui` and `reflex-curses` loads more quickly, uses less resources, and has `vim` like keybindings. There isn't much fault I can find and I've already pestered you enough with this issue you quickly resolved. Thanks for the great program.
