### ISSUE TITLE
Auto refresh current query

### ISSUE THREAD

**Issue by acerbicless** [Foldex/reflex-curses#2]
Not sure if this is the right place to ask this, apologies if not.
Is there a way to have the current page refresh every (x) seconds? 
For example, It would be great to have my followed list auto-refresh so I can leave a terminal window open and keep an eye on who is live.
Thanks

**Comment by Foldex** [comment]
No harm done in asking. 
That said, my first thought is that Twitch's API does have rate limiting, so repeatedly sending automated requests in an interval of a few seconds seems like a bad idea. I myself dont really keep RC open when I use it, as I have a keybind to launch it and have `default_state` set to `followed`, which immediately brings up the followed list on launch. Checking who is live is already pretty low friction for me.

I'm not completely against the idea, but I'd think a much saner interval would be in the span of a couple of minutes, rather than seconds. Mind you, If all you're interested in is seeing who is live, you could simply run `reflex-curses -f` with a cron or loop and pipe that into some display, rather than keeping a terminal open all the time.

**Comment by acerbicless** [comment]
Thanks for your response.
Good point with the rate limiting, a few minutes sounds far more humane!
Have had it set up as you describe (keybind and default to followed) for a few days now and it's perfect to just check who is live when you're curious, it's likely more appropriate using it like this to be fair.
Thanks again
